title: "JongHyeon Kim"
author: "JongHyeon Kim"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/jhk16"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/jonghyeon-kim-7b49bb121"}
  - {title: Google Scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=HZ19ER0AAAAJ&hl=en"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

# Analytics
analytics:
  provider               : "google-gtag" 
  # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-K7Y35D9XBE"
    anonymize_ip         : # true, false (default)


plugins:
 - jekyll-feed
